-- THE PRODUCT MGT WANTS TO KNOW THE SALES REVENUE GENERATED BY EACH PRODUCT
 SELECT 

    dp.EnglishProductName AS ProductName,
    dp.Color AS ProductColor,
    dp.Size AS ProductSize,
    SUM(SalesAmount) AS SalesAmount,
    dp.[Status] AS Status

FROM FactInternetSales AS fs
    INNER JOIN DimProduct as dp
    ON fs.ProductKey = dp.ProductKey 

WHERE dp.Status = N'Current'

GROUP BY dp.EnglishProductName, dp.Color, dp.[Size],dp.[Status]

ORDER BY SalesAmount DESC

/* Test for the number of rows in ENglish Product Name
SELECT
    EnglishProductName

FROM
    DimProduct

WHERE [Status] = N'Current'
/*